"""long_range_gamma.py — Part 2: interacting anomalous dimensions of the
long-range symplectic CFT*, by large-N (Sp(N)) algebra.

GOAL (PLAN.md, Part 2): turn a queued candidate's kinetic exponent `s` into the
*interacting* would-be-stress-tensor anomalous dimension gamma_T(s), so that the
"non-local" label from Part 1 (where gamma_T_free = 2(s-1) is only a CONVENTION
whose zero set is physical) is replaced by a derived number/series. The result is
emitted as CERTIFIED DATA for Lean to re-check, closing the handshake.

HONESTY DISCIPLINE (mirrors STATUS.md, so we do NOT repeat the Ric-trap):
  * DERIVED, exact here:
        - Delta_chi(s)      = (d - 2s)/2            (free, long-range)
        - Delta_sigma_LO(s) = 2s                    (HS marginality)
        - gamma_phi(s)      = 0                      (long-range non-renormalization
                                                      of the |p|^{2s} kinetic term)
        - the s -> 1 boundary condition gamma_T -> 0 (locality/conservation),
          enforced as a hard rail on any candidate gamma_T.
  * PHYSICS INPUT, to be evaluated (the actual research integral):
        - C_T(s, d): the order-1/N coefficient of the spin-2 broken-current
          self-energy. It is a specific conformal integral built from the toolbox
          in conformal_integrals.py. Left SYMBOLIC and clearly marked; plugging in
          its evaluated value is the one genuinely new computation. We refuse to
          fabricate a coefficient — that would be exactly the slope-of-gamma_T trap.

Run `python long_range_gamma.py` for the LO report + the s->1 consistency check.
"""

from __future__ import annotations

import json
import sympy as sp

from conformal_integrals import (
    d, s, N,
    free_dim_chi, hs_field_dim_LO, bubble_U, bubble_power, half,
)

# ---------------------------------------------------------------------------
# A. Exactly derived leading-order data
# ---------------------------------------------------------------------------

def delta_chi(dim=d, kin=s):
    """Long-range scalar dimension; exact at large N (no wavefunction renorm)."""
    return free_dim_chi(dim, kin)


def delta_sigma_LO(dim=d, kin=s):
    """HS field dimension at leading order: Delta_sigma = 2s."""
    return hs_field_dim_LO(dim, kin)


def gamma_phi(dim=d, kin=s):
    r"""Anomalous dimension of the fundamental scalar.

    For a *long-range* kinetic term |p|^{2s} with non-integer s, the would-be
    wavefunction renormalization is an analytic-in-p^2 counterterm and therefore
    cannot renormalize the non-analytic |p|^{2s} propagator. Hence gamma_phi = 0
    to all orders in 1/N (the long-range non-renormalization theorem). This is a
    genuine derived statement, not a convention.
    """
    return sp.Integer(0)


def induced_sigma_propagator_coeff(dim=d, kin=s):
    """Coefficient of the sigma propagator induced by the chi bubble.

    sigma has no bare kinetic term; its propagator is generated by the one-loop
    chi^2 bubble Pi(x) ~ |x|^{-4 Delta_chi} = |x|^{-2(d-2s)}. Inverting the bubble
    fixes Delta_sigma = d - 2 Delta_chi = 2s and gives the normalization below
    (exact, from bubble_U). This normalization is what the order-1/N self-energy
    diagrams are divided by, so it must be carried exactly.
    """
    a = delta_chi(dim, kin)
    coeff = bubble_U(a, a, dim)          # U(Delta_chi, Delta_chi)
    composite_dim = bubble_power(a, a, dim)   # = 2*Delta_chi - d/2
    return sp.simplify(coeff), sp.simplify(composite_dim)


# ---------------------------------------------------------------------------
# B. The would-be stress tensor gamma_T(s) at order 1/N  (the research piece)
# ---------------------------------------------------------------------------

# The order-1/N spin-2 broken-current coefficient. THIS is the integral to
# evaluate with the conformal_integrals toolbox; until evaluated it stays a
# symbolic function so nothing downstream silently trusts a fabricated number.
C_T = sp.Function("C_T")            # C_T(s, d): pure number per (s, d)


def gamma_T_interacting(dim=d, kin=s, evaluated_CT=None):
    r"""Interacting anomalous dimension of the would-be stress tensor.

        gamma_T(s) = (1/N) * C_T(s, d) + O(1/N^2),

    with the HARD physical constraint  C_T(1, d) = 0  (at s = 1 the theory is
    local, the spin-2 current is conserved, gamma_T = 0). If `evaluated_CT` is
    provided (a sympy expr in s, d from the loop integral), it is substituted and
    the local limit is asserted; otherwise the symbolic form is returned so the
    caller cannot mistake a placeholder for a result.
    """
    expr = C_T(kin, dim) / N
    if evaluated_CT is not None:
        expr = sp.simplify(evaluated_CT / N)
    return expr


def assert_local_limit(evaluated_CT, dim=d):
    """Rail: any candidate C_T(s,d) MUST vanish at s = 1 (conservation). Returns
    the (simplified) value at s=1; raises if it is not identically zero."""
    val = sp.simplify(evaluated_CT.subs(s, 1))
    if val != 0:
        raise AssertionError(
            f"C_T(1, d) = {val} != 0 violates s->1 stress-tensor conservation; "
            "the candidate gamma_T is physically inconsistent."
        )
    return val


# ---------------------------------------------------------------------------
# C. Handshake: emit certified data for Lean (Part 1 <-> Part 2 contract)
# ---------------------------------------------------------------------------

def certified_record(s_value, dim_value=3, evaluated_CT=None, N_order=1):
    """Produce the JSON handshake record described in PLAN.md:
        {s, gamma_T_interacting, gamma_phi, N_order, delta_chi, delta_sigma}.

    `s_value`, `dim_value` numeric; `evaluated_CT` optional sympy expr in (s,d).
    gamma_T is reported symbolically (string) unless C_T has been evaluated, in
    which case the numeric 1/N coefficient is included and the local limit checked.
    """
    subs0 = {d: dim_value, s: s_value}
    rec = {
        "s": float(s_value),
        "d": float(dim_value),
        "delta_chi": float(sp.simplify(delta_chi().subs(subs0))),
        "delta_sigma_LO": float(sp.simplify(delta_sigma_LO().subs(subs0))),
        "gamma_phi": float(gamma_phi()),
        "N_order": N_order,
        "local": bool(sp.simplify(sp.Eq(sp.Rational(s_value).limit_denominator(10**9), 1))),
    }
    if evaluated_CT is not None:
        assert_local_limit(evaluated_CT, d)
        ct_val = float(sp.simplify(evaluated_CT.subs(subs0)))
        rec["C_T"] = ct_val
        rec["gamma_T_coeff_over_N"] = ct_val          # gamma_T = this / N
        rec["gamma_T_status"] = "derived"
    else:
        rec["C_T"] = None
        rec["gamma_T_status"] = "symbolic — C_T(s,d) integral not yet evaluated"
    return rec


# ---------------------------------------------------------------------------
# D. Self-test / report
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    print("=== Long-range symplectic CFT* — Part 2 leading-order report ===\n")
    print("Delta_chi(s)        =", sp.simplify(delta_chi()))
    print("Delta_sigma_LO(s)   =", sp.simplify(delta_sigma_LO()), " (= 2s)")
    print("gamma_phi(s)        =", gamma_phi(), " (long-range non-renormalization)\n")

    coeff, cdim = induced_sigma_propagator_coeff()
    print("induced sigma-prop coeff U(Dchi,Dchi) =", coeff)
    print("  composite dim 2*Dchi - d/2          =", cdim, "\n")

    print("gamma_T(s) symbolic =", gamma_T_interacting(), "  (C_T to be evaluated)\n")

    # Demonstrate the rail with a TOY ansatz that respects conservation:
    #   C_T_toy = k*(s-1)  vanishes at s=1 -> passes; report at d=3, s=1.4.
    k = sp.symbols("k")
    C_T_toy = k * (s - 1)
    print("toy C_T = k*(s-1); local-limit check C_T(1,d) =",
          assert_local_limit(C_T_toy), "(passes rail)")

    rec_symbolic = certified_record(sp.Rational(7, 5), 3)            # s = 1.4
    print("\nhandshake (symbolic gamma_T):")
    print(json.dumps(rec_symbolic, indent=2))

    rec_toy = certified_record(sp.Rational(7, 5), 3, evaluated_CT=C_T_toy.subs(k, 2))
    print("\nhandshake (toy evaluated C_T = 2*(s-1)):")
    print(json.dumps(rec_toy, indent=2))
